
name: CI


on: #trigger được hiểu là điều kiện để action này chạy
  
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  build: #tên của job
    runs-on: ubuntu-latest #hệ điều hành mà job chạy
    steps:
      - uses: actions/checkout@v4 #sử dụng action để kiểm tra mã nguồn của repo

      - name: Run a one-line script # tên của step
        run: echo Hello, world! #tác vụ

      - name: Run a multi-line script # tên của step
        run: |
          echo Add other actions to build, 
          echo test, and deploy your project.  
        | #tác vụ 

